[versions]
kotlin = "2.3.10"
compose = "1.11.0-alpha02"
themeDetector = "3.9.1"
material3 = "1.9.0"

[libraries]
compose-resources = { module = "org.jetbrains.compose.components:components-resources", version = "1.11.0-alpha02" }
material = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
material-iconsExtended = { module = "org.jetbrains.compose.material:material-icons-extended", version = "1.7.3" }
theme-detector = { module = "com.github.Dansoftowner:jSystemThemeDetector", version.ref = "themeDetector" }
catppuccin = { module = "com.catppuccin:catppuccin-palette", version = "2.0.3" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

compose = { id = "org.jetbrains.compose", version.ref = "compose" }
